id: app-controller
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: app
  # This is identical to the pod config above
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: app
        containers:
          - name: app
            image: registry.appdev.io/roadrunner120485/spring-boot-docker:b8
            cpu: 1000
            ports:
              - name: web
                containerPort: 8080
    labels:
      name: app